trigger:
- master

pool:
  name: default

variables:
  reportName: 'WEB Lokal Pipeline Report'

parameters:
  - name: TagName
    displayName: TagName
    default: '@smoke'
    type: string

steps:

- script: |
    gem install bundler
    bundle install
  displayName: 'bundle install'

- script: |
    bundle exec cucumber --tags "${{parameters.TagName}}" headless=true browser=chrome
  displayName: 'Running Test'