trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  reportName: 'WEB Lokal Pipeline Report'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'

- script: |
    bundle install
  displayName: 'Running Test'