trigger:
- master

pool:
  name: default

variables:
  reportName: 'WEB Lokal Pipeline Report'

parameters:
  - name: TagName
    displayName: TagName
    default: '@smoke'
    type: string

  - name: Headless
    displayName: Headless
    default: true
    type: boolean    

steps:

- script: |
    gem install bundler
    bundle install
  displayName: 'bundle install'

- script: |
    bundle exec cucumber --tags "${{parameters.TagName}}" headless=${{parameters.Headless}} browser=chrome
  displayName: 'Running Test'