trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  reportName: 'WEB Lokal Pipeline Report'

parameters:
  - name: TagName
    displayName: TagName
    default: '@smoke'
    type: string

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'

- script: |
    gem install bundler
    bundle install
  displayName: 'bundle install'

- script: |
    bundle exec cucumber --tags "${{parameters.TagName}}" headless=true browser=chrome
  displayName: 'Running Test'